### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RebekkaAalbers**
Updates TOC after team discussion. 
Adds names to certain topics.

@AhmedSalih-PowerPlatformPlace, @angelogulisano and I discussed the TOC during our Teams meetup and made changes while discussing. 
@LuiseFreese, we saw you are now assigned to another team. We removed quite a number of items from the list we think fits better in the advanced topics, like using monitor and test studio.

### CODE REVIEW

**Comment by RebekkaAalbers** [comment]
@microsoft-github-policy-service agree

**Comment by LuiseFreese** [comment]
@RebekkaAalbers - uhm... no, I was not moved to another team, I contribute to two topics - Power Apps Development and Advanced Topics.

**Comment by LuiseFreese** [comment]
@RebekkaAalbers - uhm... no, I was not moved to another team, I contribute to two topics - Power Apps Development and Advanced Topics.

**Comment by RebekkaAalbers** [comment]
Ah, ok. In Frank's post on Teams you where no longer assigned to Power Apps development.

**Comment by LuiseFreese** [comment]
Hope you all didn’t throw me out?! 😅

Luise Freese
Microsoft 365 & Power Platform Consultant
Dual Microsoft MVP M365 Development & Business Applications


based in Germany: Uerdinger Str. 26 | 40474 Düsseldorf
but always traveling ✈✈✈
________________________________

**Comment by RebekkaAalbers** [comment]
@LuiseFreese, no, definitely not! We're happy if you contribute. 😊

**Review by FBoucher — APPROVED** [review]
❤️

**Pull request merged**
