### PR TITLE
Advanced Topics TOC

### PR DESCRIPTION
**Pull request by julians1966**
Created assets folder
Added Custom Connectors from Power Automate
Removed AI/Copilot

### CODE REVIEW

**Comment by julians1966** [comment]
@microsoft-github-policy-service agree

**Comment by julians1966** [comment]
@LuiseFreese

**Review by FBoucher — APPROVED** [review]
Nice start!

**Comment by LuiseFreese** [comment]
[heart]         Luise Freese reacted to your message:
________________________________

**Pull request merged**
